--- !ruby/struct:Qc::ProjectSettings
project_id: 3899983
file_extensions: cs
last_sync_at: 2020-02-15 16:01:08.631662000 +07:00
last_compile_id: 
last_backtest_id: 
ignored_files:
- AssemblyInfo.cs
name: 
execution_count: 1
